module "functions" {
  source = "./modules/functions"

  GOOGLE_PROJECT_ID      = var.GOOGLE_PROJECT_ID
  SLACK_USER_OAUTH_TOKEN = var.SLACK_USER_OAUTH_TOKEN
  SLACK_BOT_OAUTH_TOKEN  = var.SLACK_BOT_OAUTH_TOKEN
  SLACK_CHANNEL_ID       = var.SLACK_CHANNEL_ID
  SLACK_CHANNEL_ID_RSS   = var.SLACK_CHANNEL_ID_RSS
}
